### ISSUE TITLE
Publish to HACS (or HA)

### ISSUE THREAD

**Issue by ProLoser** [Sennevds/media_player.template#1]
Wow this is awesome! This seems like it may be viable candidate for HACS if not merging upstream into HA itself?

**Comment by Sennevds** [comment]
First I want to have it more complete. Also I need to read more about components so that I use the right methods and everything. But will let you know. 
If you're missing a feature make a new issue. At this moment I've implemented the features I needed.

**Comment by Tloram** [comment]
Great job on this, works a charm for my use case. Integrating Logitech Harmony as a media_player and then exposing via HA Cloud to Alexa. This allows me to control TVs in separate rooms using Alexa's room aware commands like "Turn on TV, Pause, Play, Turn off TV". Pretty much the Holy Grail for Logitech Harmony + Alexa users, the number of times I have seen this question asked on Reddit, and now here it is working via HA and you custom component!

**Comment by ColinRobbins** [comment]
This is working great for me.
I second the request, for it to be added via HACS.

**Comment by Sennevds** [comment]
You can add this repo as custom_repository. I've added a pull request to add the default repositories

**Comment by ProLoser** [comment]
Do you have a link to the PR for upvoting?

**Comment by Sennevds** [comment]
I still need to fix some other stuff. First thing I need is a brand logo for the integration.
I took the original template logo but that isn't allowed apparently.

**Comment by Sennevds** [comment]
I've fixed everything needed for the pr it only needs to be approved: https://github.com/hacs/default/pull/679

**Comment by Sennevds** [comment]
The pr is merged!

**Comment by Shulyaka** [comment]
Hi! What about upstreaming to HA core? This looks like a perfect integration for HA.

**Comment by Sennevds** [comment]
> Hi! What about upstreaming to HA core? This looks like a perfect integration for HA.

It's a possibility but I think the integration still has several stuff missing before it could be fully integrated in HA
