### ISSUE TITLE
Do you want me to add GitHub Actions?

### ISSUE THREAD

**Issue by KTibow** [Sennevds/media_player.template#10]
If you want, I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

**Comment by Sennevds** [comment]
What kind of actions do you want to add?

**Comment by KTibow** [comment]
I can contribute hassfest and HACS validation, the [recognized combo](https://hacs.xyz/docs/publish/action) by HACS, and I can add flake8 to your preferences if you want. I can also contribute optional auto-formatting that amends to the last commit.

**Comment by Sennevds** [comment]
Sure any help is always welcome!

**Comment by KTibow** [comment]
Packaged or independent? I made a combined GH action, but it's totally optional, however it means that it will constantly get better.

**Comment by Sennevds** [comment]
packaged is all right.
