### ISSUE TITLE
0.118.0 - AttributeError: 'Template' object has no attribute 'extract_entities'

### ISSUE THREAD

**Issue by fufs** [Sennevds/media_player.template#13]
After updating media_player.template does not start. This is due [#42601](https://github.com/home-assistant/core/pull/42601)

**Comment by Sennevds** [comment]
Are you using the latest version?

**Comment by fufs** [comment]
Not sure. Will update and come back to you.

**Comment by fufs** [comment]
Ok, update fixes it. Not sure why I haven't tried this right away. Thank you for your reply.
