### ISSUE TITLE
What is the purpose of this template?

### ISSUE THREAD

**Issue by spudje** [Sennevds/media_player.template#14]
Maybe I'm just stupid, but what can you do with this integration? I cannot derive that from the description.

**Comment by Sennevds** [comment]
For me it was the following https://community.home-assistant.io/t/media-player-template/203062. So I had several switches that could control a receiver(by using ir commands) but then you would need to create a interface for all this switches. Now I can just create a new media player entity and use like mini-media-player and control my receiver.

Others have created a media_player entity out of the steam integration so he has a now playing feature in his lovelace.

**Comment by spudje** [comment]
Aha, clear. Cool, I will look into this in the future I guess. thanks!
