### ISSUE TITLE
About sound mode template

### ISSUE THREAD

**Issue by darkleliel** [Sennevds/media_player.template#16]
Hi
Is there possible adding a "sound mode template" feature?
And how about adding a switch for "one button control source" (IR remoted, can not be specified)?

**Comment by Sennevds** [comment]
I will try to implement sound mode this week!
For the second part you push the same button several times to change the input source?

**Comment by darkleliel** [comment]
> I will try to implement sound mode this week!
> For the second part you push the same button several times to change the input source?

Glad to have your reply!
About the second part, that is correct, my speaker source can be change by the "source" button on IR remote, and the source will cycle through several options (usb/aux/bluetooth/etc).

**Comment by Sennevds** [comment]
You could just add random inputs and every time you change the input you send the same code.

**Comment by darkleliel** [comment]
OK...I set a string on 'current_source_template' and it works great...XD
