### ISSUE TITLE
media_series missing _title in code

### ISSUE THREAD

**Issue by Seperis** [Sennevds/media_player.template#18]
media_series_title isn't working due to this bit of code:  

Problem:
Line 437:  "_media_series", self._media_series_title_template

Correction:
 "_media_series" to "_media_series_title"

Tested in my copy in HA and that fixed the problem. Otherwise is working fantastically.

**Comment by Sennevds** [comment]
Ah that's stupid of me. Could you make a pull request for it?

**Comment by Sennevds** [comment]
Closed by #19

**Comment by Seperis** [comment]
Done.  I'm still new to github and that's about my second pull so tell me if I'm following accepted standard. 

As soon as I can find a way to integrate my polk soundbar into HA to get direct access to it's HDMI's (now all I can get access to now is sound through alexa media), this template will control the entire media setup in my room.

**Comment by Sennevds** [comment]
> Done. I'm still new to github and that's about my second pull so tell me if I'm following accepted standard.
> 
> As soon as I can find a way to integrate my polk soundbar into HA to get direct access to it's HDMI's (now all I can get access to now is sound through alexa media), this template will control the entire media setup in my room.

PR was okay! For your soundbar I don't know what you want to do but maybe you can control it by IR that's how I control an older Harman & Kardon receiver.

**Comment by Seperis** [comment]
> PR was okay! For your soundbar I don't know what you want to do but maybe you can control it by IR that's how I control an older Harman & Kardon receiver.

I'm using the remote now to change the HDMI source on the polk soundbar, but truthfully, with two separate HDMI sources (TV's three and soundbar's two) I probably will need to wait until hdmi_cec is fully functional again and hard code the addresses into the template since the polk is a sub of the TV's HDMI2.

Right now your template covers the media players for my Samsung TV, Polk Soundbar, Nvidia Shield TV, and Plex Server that runs on the Shield. I can directly control TV on/off and source and can change volume/mute the soundbar volume as well as mirror my actions to both the TV's media player and the soundbar's media player.  I can also see what is now playing on the TV, Shield TV, and Plex, match state, and perform play, next, back, pause, and stop for whatever is playing and it also mirrors back to the individual media players in (almost depending on how fast HA's services run) realtime. So that's seriously awesome.   

I added, tested, and am using every action and template in media_player_template you have available but seek (action) and the ones related to music: artist_template, album_template, album_art_template, and media_album_artist_template.  That's pretty much only because I haven't gotten around to testing music yet, just visual media; I'm currently working to get the visual information of the template player to exactly match each device's individual media player and so far, the only one that's still in progress is the Shield TV; the Plex Media Player and the Media Player Template when showing Plex are now an exact match.

Thank you for your work on this!  This has been incredibly fun to configure and learn how to use.
