### ISSUE TITLE
Universal Media Player

### ISSUE THREAD

**Issue by dgomes** [Sennevds/media_player.template#22]
Are you aware of https://www.home-assistant.io/integrations/universal/ ?

**Comment by Sennevds** [comment]
Yes but this integrations requires existing media_player entities. The integration I created can make a media_player entity from scratch.

**Comment by dgomes** [comment]
Got you!

I think you should open a PR to have it added to core :)

**Comment by Sennevds** [comment]
I think at first I keep it as a custom_component so it can be used and the bugs are found and when I think it's kind of complete I will make a pr to get it in the core.
I'm going to close this issue but you can always reopen it when there's anything else!
