### ISSUE TITLE
Add Version key in json

### ISSUE THREAD

**Issue by jokerigno** [Sennevds/media_player.template#28]
Hi,

I found a warning message in logs. I'm quite sure that you already know it but if don't please have a look at it:

No 'version' key in the manifest file for custom integration 'media_player_template'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'media_player_template'

**Comment by Sennevds** [comment]
Are you using the latest version? as you can see here it has a version: https://github.com/Sennevds/media_player.template/blob/43115cc124811b638d0dde4e90e857d75e38dab8/custom_components/media_player_template/manifest.json#L10

**Comment by jokerigno** [comment]
Nope. Updated and now it's gone!
