### ISSUE TITLE
Error when adding current_source_template and mute_action

### ISSUE THREAD

**Issue by fufs** [Sennevds/media_player.template#3]
When those options are added to configuration.yaml it throws an error saying that those options are incorrect for this component. Without them and with other defaults (from README.md) it passes no problem.

**Comment by Sennevds** [comment]
Hi,

I haven't used these options myself will test them this week

**Comment by Sennevds** [comment]
I've updated the repo no it should both work. watch out because the custom component name is changed

**Comment by fufs** [comment]
Thanks, I'll check it out tomorrow

**Comment by Sennevds** [comment]
Should be fixed now
