### ISSUE TITLE
value_template doesn't seem to be working

### ISSUE THREAD

**Issue by J-Pipe** [Sennevds/media_player.template#4]
The state of my media player is always off, even though my value_template is returning "on".

platform: template
  media_players:
    upstairs:
      friendly_name: Upstairs
      value_template: >
        {% if is_state("input_boolean.upstairs_music_power", "on") -%}
          on
        {%- else -%}
          off
        {%- endif %}
      turn_on:
        service: input_boolean.turn_on
        data_template:
          entity_id: input_boolean.upstairs_music_power
      turn_off:
        service: input_boolean.turn_off
        data_template:
          entity_id: input_boolean.upstairs_music_power
      volume_up:
        service: input_number.increment
        data_template:
          entity_id: input_number.upstairs_music_volume
      volume_down:
        service: input_number.decrement
        data_template:
        entity_id: input_number.upstairs_music_volume

**Comment by Sennevds** [comment]
Could you try following:
```
value_template: >
{{ states("input_boolean.upstairs_music_power") }}
```

**Comment by J-Pipe** [comment]
No luck

**Comment by Sennevds** [comment]
Could you try again I've updated the repo watch out because the custom component name is changed

**Comment by J-Pipe** [comment]
idk what I'm doing wrong, but I'm getting this error after renaming everything now

`ERROR (MainThread) [homeassistant.setup] Setup failed for media_player: No setup function defined.`

**Comment by Sennevds** [comment]
Could you share your current config?

**Comment by Sennevds** [comment]
I've updated the repo could you test again?

**Comment by J-Pipe** [comment]
Works now. Thanks!
