### ISSUE TITLE
Deprecated supported features values - HA Core 2024.01.0b2 and above

### ISSUE THREAD

**Issue by ResteNarquois** [Sennevds/media_player.template#47]
Startup of HA Core 2024.01.0b2 and above presents a deprecation message in the logs:

`
Entity media_player.xxxx (<class 'custom_components.media_player_template.media_player.MediaPlayerTemplate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|TURN_ON|TURN_OFF|VOLUME_STEP|SELECT_SOURCE|STOP|PLAY|SELECT_SOUND_MODE: 89529>, please create a bug report at https://github.com/Sennevds/media_player.template/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
`

Seems there's quite a long time to address this though, and the created media players continue to function as normal:

**Comment by golles** [comment]
@ResteNarquois since you've reported this, could you test out my PR #48

**Comment by ResteNarquois** [comment]
Everything works fine here - thanks to you both for picking this up so quickly

**Comment by golles** [comment]
No worries, thank you for confirming!
