### ISSUE TITLE
Receiving message in HA log that media_player.template is using depreciating features that will be unavailable in 2025

### ISSUE THREAD

**Issue by lambros414** [Sennevds/media_player.template#51]
The message in my log file is:

(MainThread) [homeassistant.helpers.entity] Entity media_player.now_playing (<class 'custom_components.media_player_template.media_player.MediaPlayerTemplate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.TURN_ON|TURN_OFF|VOLUME_STEP|SELECT_SOURCE|SELECT_SOUND_MODE: 68992>, please create a bug report at https://github.com/Sennevds/media_player.template/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

I love this template and is making my life so much easier.  Is this on anyone's radar to be fixed?

**Comment by lambros414** [comment]
Hi.  Touching base on this issue again.  I have been seeing it for a while and haven't seen any comments or updates

Is anyone maintaining this code any longer?

Thanks!

**Comment by borez** [comment]
Hi, chiming here too.

Am getting these warning messages post upgrade to 2024.3.0

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1597
First occurred: 8:42:57 PM (2 occurrences)
Last logged: 8:43:04 PM

Entity media_player.tdai_1120 (<class 'custom_components.media_player_template.media_player.MediaPlayerTemplate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|VOLUME_STEP|SELECT_SOURCE|SELECT_SOUND_MODE: 69004>, please create a bug report at https://github.com/Sennevds/media_player.template/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE: 9>, please report it to the author of the 'smartir' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by WendelFelius** [comment]
SUPPORT_TURN_OFF was used from media_player_template, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.TURN_OFF instead, please report it to the author of the 'media_player_template' custom integration
SUPPORT_TURN_ON was used from media_player_template, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.TURN_ON instead, please report it to the author of the 'media_player_template' custom integration
SUPPORT_VOLUME_MUTE was used from media_player_template, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_MUTE instead, please report it to the author of the 'media_player_template' custom integration
SUPPORT_VOLUME_SET was used from media_player_template, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_SET instead, please report it to the author of the 'media_player_template' custom integration
SUPPORT_VOLUME_STEP was used from media_player_template, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaPlayerEntityFeature.VOLUME_STEP instead, please report it to the author of the 'media_player_template' custom integration

**Comment by dy-nz** [comment]
And...
SUPPORT_NEXT_TRACK was used from media_player_template, this is a deprecated constant ...
SUPPORT_PAUSE was used from media_player_template, this is a deprecated constant ...
SUPPORT_PLAY was used from media_player_template, this is a deprecated constant ...
SUPPORT_PLAY_MEDIA was used from media_player_template, this is a deprecated constant ...
SUPPORT_PREVIOUS_TRACK was used from media_player_template, this is a deprecated constant ...
SUPPORT_SEEK was used from media_player_template, this is a deprecated constant ...
SUPPORT_SELECT_SOUND_MODE was used from media_player_template, this is a deprecated constant ...
SUPPORT_SELECT_SOURCE was used from media_player_template, this is a deprecated constant ...
SUPPORT_STOP was used from media_player_template, this is a deprecated constant ...

**Comment by alexcaoys** [comment]
By the way, looks like this is already fixed (https://github.com/Sennevds/media_player.template/commit/b3157342bc06b67b191f9bc8c9c5b005d7b217c5) but hasn't been published to HACS. 

Hi @Sennevds , are we going to have an update on HACS? 

Thanks!

**Comment by Sennevds** [comment]
Sorry for the late reaction. I've just created a new release.
